# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8e7df87c94ff6a705f36f389bfbcb7e966b6d39fcc2228d4dada51fce40bf4bce215269fc3b34ef07d1bbb73909c0855e4ba5a736f4d05bfaeb93d63e07dd5

test:
  secret_key_base: 7cf5b783ca999446cfc1c455bdb2c48428426b8ef76115f1935be1ffeb9fdd84803cd9e25a1c4c6d72e8bce561f4e5509e932024da01df577220ce6bde2c883b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
